<a href="https://colab.research.google.com/github/sbrgothub/Turkey_Online_Retail_New/blob/main/Product_Recomendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Necessary package and csv to dataframe

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/luminar/data_science/ML/resume/archive (1)/ecommerce_customer_behavior_dataset_v2.csv")

# Data_Preprocessing

date format conversion (object - date)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

Discount %

In [ ]:
df['Discount_%']=(df['Discount_Amount']/df['Total_Amount'])*100

Age

In [ ]:
pd.cut(df['Age'],bins=3).value_counts()

Age
(17.943, 37.0]    10140
(37.0, 56.0]       6378
(56.0, 75.0]        531
Name: count, dtype: int64

In [ ]:
x=df.copy()

In [ ]:
def ager(age):
  if age>17 and age<=37:
    return 'young'
  elif age>37 and age<=56:
    return 'middle'
  else:
    return 'old'

In [ ]:
x['Age_Group']=x['Age'].apply(ager)

Discount Division

1.   Session_Duration Division
2.   Pages_Viewed Range

In [ ]:
x['Session_Duration_Minutes']=pd.cut(x['Session_Duration_Minutes'],bins=3,labels=['low_time','medium_time','high_time'])
x['Pages_Viewed']=pd.cut(x['Pages_Viewed'],bins=3,labels=['low_view','medium_view','high_view'])

In [ ]:
x['Quantity']=pd.cut(x['Quantity'],bins=5,labels=['Qnt_1','Qnt_2','Qnt_3','Qnt_4','Qnt_5'])
x['Customer_Rating']=pd.cut(x['Customer_Rating'],bins=5,labels=['Rate_1','Rate_2','Rate_3','Rate_4','Rate_5'])

Products Named Grouped by Price range

In [ ]:
rater=x.copy()

In [ ]:
rater['Product']=''
rater=rater.iloc[:0,:]
rater

Empty DataFrame
Columns: [Order_ID, Customer_ID, Date, Age, Gender, City, Product_Category, Unit_Price, Quantity, Discount_Amount, Total_Amount, Payment_Method, Device_Type, Session_Duration_Minutes, Pages_Viewed, Is_Returning_Customer, Delivery_Time_Days, Customer_Rating, Discount_%, Age_Group, Product]
Index: []

[0 rows x 21 columns]

In [ ]:
for i in x['Product_Category'].unique():
  product_i=x.loc[x['Product_Category']==i]

  # price range:
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])

  # Product Divided based on Price
  price=product_i['Unit_Price'].sort_values(ascending=False).unique()
  cnt=1
  print('________________')
  print('_++++++++++++++')
  print(price)
  print('_______________')
  print('++++++++++++++++++')
  for j in price:
    product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)
    cnt+=1
  rater=pd.concat([rater,product_i],ignore_index=True)

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[255.38 253.1  237.66 ...  10.31  10.3    9.82]
_______________
++++++++++++++++++

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[2963.86 2941.11 2900.17 ...   55.68   53.54   53.21]
_______________
++++++++++++++++++

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[2146.11 2140.77 2057.15 ...   35.77   33.98   30.63]
_______________
++++++++++++++++++

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[289.5  284.23 256.48 ...   6.3    5.78   5.05]
_______________
++++++++++++++++++

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[466.07 457.   446.39 ...  16.74  16.12  15.97]
_______________
++++++++++++++++++

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[750.38 691.08 673.61 ...  16.66  16.6   14.39]
_______________
++++++++++++++++++

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[1732.85 1286.14 1260.84 ...   23.79   21.23   19.74]
_______________
++++++++++++++++++

/tmp/ipykernel_1070/2471504805.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i['Price_Range']=pd.cut(product_i['Unit_Price'],bins=3,labels=['low_price','medium_price','high_price'])
/tmp/ipykernel_1070/2471504805.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  product_i.loc[product_i['Unit_Price']==j,'Product']=str(i)+':'+str(cnt)

________________
_++++++++++++++
[7900.01 7570.41 7440.42 ...  161.21  157.35  133.57]
_______________
++++++++++++++++++

In [ ]:
rater

,Order_ID,Customer_ID,Date,Age,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,...,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Discount_%,Age_Group,Product,Price_Range
0,ORD_000001-1,CUST_00001,2023-05-29,40,Male,Ankara,Books,29.18,Qnt_1,0.00,...,Mobile,medium_time,medium_view,True,13,Rate_4,0.000000,middle,Books:1525,low_price
1,ORD_000010-2,CUST_00010,2023-12-17,41,Male,Kayseri,Books,109.25,Qnt_5,0.00,...,Mobile,medium_time,medium_view,True,10,Rate_5,0.000000,middle,Books:189,medium_price
2,ORD_000011-6,CUST_00011,2024-01-13,29,Male,Kayseri,Books,20.54,Qnt_2,0.00,...,Mobile,medium_time,medium_view,True,5,Rate_4,0.000000,young,Books:1796,low_price
3,ORD_000014-3,CUST_00014,2023-10-08,18,Female,Konya,Books,19.95,Qnt_1,0.00,...,Mobile,medium_time,medium_view,True,6,Rate_4,0.000000,young,Books:1816,low_price
4,ORD_000015-4,CUST_00015,2023-10-15,18,Male,Ankara,Books,129.65,Qnt_2,38.85,...,Desktop,low_time,medium_view,True,4,Rate_4,17.623044,young,Books:103,medium_price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17044,ORD_004989-3,CUST_04989,2023-04-29,37,Female,Konya,Electronics,1617.68,Qnt_3,741.82,...,Mobile,medium_time,medium_view,True,4,Rate_5,18.043792,young,Electronics:886,low_price
17045,ORD_004992-2,CUST_04992,2024-02-08,43,Male,Istanbul,Electronics,1969.28,Qnt_4,0.00,...,Mobile,medium_time,low_view,True,1,Rate_5,0.000000,middle,Electronics:689,low_price
17046,ORD_004993-3,CUST_04993,2023-03-03,33,Female,Adana,Electronics,2113.52,Qnt_1,307.30,...,Mobile,high_time,medium_view,True,4,Rate_2,17.013431,young,Electronics:617,low_price
17047,ORD_004993-9,CUST_04993,2024-03-17,33,Female,Adana,Electronics,2007.72,Qnt_4,0.00,...,Desktop,medium_time,high_view,True,3,Rate_4,0.000000,young,Electronics:670,low_price
17048,ORD_004997-2,CUST_04997,2023-03-15,43,Female,Adana,Electronics,3109.97,Qnt_4,0.00,...,Desktop,medium_time,medium_view,True,2,Rate_5,0.000000,middle,Electronics:295,medium_price

In [ ]:
x=rater.iloc[:,4:].copy()

In [ ]:
x

,Gender,City,Product_Category,Unit_Price,Quantity,Discount_Amount,Total_Amount,Payment_Method,Device_Type,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Delivery_Time_Days,Customer_Rating,Discount_%,Age_Group,Product,Price_Range
0,Male,Ankara,Books,29.18,Qnt_1,0.00,29.18,Digital Wallet,Mobile,medium_time,medium_view,True,13,Rate_4,0.000000,middle,Books:1525,low_price
1,Male,Kayseri,Books,109.25,Qnt_5,0.00,546.25,Debit Card,Mobile,medium_time,medium_view,True,10,Rate_5,0.000000,middle,Books:189,medium_price
2,Male,Kayseri,Books,20.54,Qnt_2,0.00,41.08,Debit Card,Mobile,medium_time,medium_view,True,5,Rate_4,0.000000,young,Books:1796,low_price
3,Female,Konya,Books,19.95,Qnt_1,0.00,19.95,Credit Card,Mobile,medium_time,medium_view,True,6,Rate_4,0.000000,young,Books:1816,low_price
4,Male,Ankara,Books,129.65,Qnt_2,38.85,220.45,Cash on Delivery,Desktop,low_time,medium_view,True,4,Rate_4,17.623044,young,Books:103,medium_price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17044,Female,Konya,Electronics,1617.68,Qnt_3,741.82,4111.22,Digital Wallet,Mobile,medium_time,medium_view,True,4,Rate_5,18.043792,young,Electronics:886,low_price
17045,Male,Istanbul,Electronics,1969.28,Qnt_4,0.00,7877.12,Credit Card,Mobile,medium_time,low_view,True,1,Rate_5,0.000000,middle,Electronics:689,low_price
17046,Female,Adana,Electronics,2113.52,Qnt_1,307.30,1806.22,Credit Card,Mobile,high_time,medium_view,True,4,Rate_2,17.013431,young,Electronics:617,low_price
17047,Female,Adana,Electronics,2007.72,Qnt_4,0.00,8030.88,Credit Card,Desktop,medium_time,high_view,True,3,Rate_4,0.000000,young,Electronics:670,low_price
17048,Female,Adana,Electronics,3109.97,Qnt_4,0.00,12439.88,Debit Card,Desktop,medium_time,medium_view,True,2,Rate_5,0.000000,middle,Electronics:295,medium_price

In [ ]:
x=x.drop(columns=['Unit_Price','Delivery_Time_Days'])

In [ ]:
list(x.iloc[:,4:8].columns)

['Discount_Amount', 'Total_Amount', 'Payment_Method', 'Device_Type']

In [ ]:
x=x.drop(columns=list(x.iloc[:,4:8].columns))

In [ ]:
x

,Gender,City,Product_Category,Quantity,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Customer_Rating,Discount_%,Age_Group,Product,Price_Range
0,Male,Ankara,Books,Qnt_1,medium_time,medium_view,True,Rate_4,0.000000,middle,Books:1525,low_price
1,Male,Kayseri,Books,Qnt_5,medium_time,medium_view,True,Rate_5,0.000000,middle,Books:189,medium_price
2,Male,Kayseri,Books,Qnt_2,medium_time,medium_view,True,Rate_4,0.000000,young,Books:1796,low_price
3,Female,Konya,Books,Qnt_1,medium_time,medium_view,True,Rate_4,0.000000,young,Books:1816,low_price
4,Male,Ankara,Books,Qnt_2,low_time,medium_view,True,Rate_4,17.623044,young,Books:103,medium_price
...,...,...,...,...,...,...,...,...,...,...,...,...
17044,Female,Konya,Electronics,Qnt_3,medium_time,medium_view,True,Rate_5,18.043792,young,Electronics:886,low_price
17045,Male,Istanbul,Electronics,Qnt_4,medium_time,low_view,True,Rate_5,0.000000,middle,Electronics:689,low_price
17046,Female,Adana,Electronics,Qnt_1,high_time,medium_view,True,Rate_2,17.013431,young,Electronics:617,low_price
17047,Female,Adana,Electronics,Qnt_4,medium_time,high_view,True,Rate_4,0.000000,young,Electronics:670,low_price
17048,Female,Adana,Electronics,Qnt_4,medium_time,medium_view,True,Rate_5,0.000000,middle,Electronics:295,medium_price

In [ ]:
x=x.drop(columns='Discount_%')

Fial dataframe with necessary features

In [ ]:
x

,Gender,City,Product_Category,Quantity,Session_Duration_Minutes,Pages_Viewed,Is_Returning_Customer,Customer_Rating,Age_Group,Product,Price_Range
0,Male,Ankara,Books,Qnt_1,medium_time,medium_view,True,Rate_4,middle,Books:1525,low_price
1,Male,Kayseri,Books,Qnt_5,medium_time,medium_view,True,Rate_5,middle,Books:189,medium_price
2,Male,Kayseri,Books,Qnt_2,medium_time,medium_view,True,Rate_4,young,Books:1796,low_price
3,Female,Konya,Books,Qnt_1,medium_time,medium_view,True,Rate_4,young,Books:1816,low_price
4,Male,Ankara,Books,Qnt_2,low_time,medium_view,True,Rate_4,young,Books:103,medium_price
...,...,...,...,...,...,...,...,...,...,...,...
17044,Female,Konya,Electronics,Qnt_3,medium_time,medium_view,True,Rate_5,young,Electronics:886,low_price
17045,Male,Istanbul,Electronics,Qnt_4,medium_time,low_view,True,Rate_5,middle,Electronics:689,low_price
17046,Female,Adana,Electronics,Qnt_1,high_time,medium_view,True,Rate_2,young,Electronics:617,low_price
17047,Female,Adana,Electronics,Qnt_4,medium_time,high_view,True,Rate_4,young,Electronics:670,low_price
17048,Female,Adana,Electronics,Qnt_4,medium_time,medium_view,True,Rate_5,middle,Electronics:295,medium_price

# vectorizing

process: Single row for each product in dataframe for vectorization

how done:
>Columns are classes of main features.
*   ex: df column=[Gender,Price_Range,Product], new df column= [Male,Female,Other,low_price,medium_price,high....]

>Values are sorted valuecounts of column for each Product.
*   ex; prod 1, prod 2 be two prod, if prod1 has valuecount for male>other>female,  male female other values in new df are : male1 other 2 female3 (even if had value_count=0).

Aim:
> vectorization and then cosine similarity for each ind products

Trial code:

In [ ]:
srt={'a':33,'b':30,'c':33,'d':29,'e':33}
srt=dict(sorted(srt.items(),key=lambda item: item[1], reverse=True))

grd_chck={'a':'','b':'','c':'','d':'','e':''}

In [ ]:
finish=set([])
cnt=1
for i in srt.items():
  finish.add(i[1])
  srt[i[0]]=f'{i[0]}{len(finish)}'
srt

{'a': 'a1', 'c': 'c1', 'e': 'e1', 'b': 'b2', 'd': 'd3'}

In [ ]:
update={}

for pr in x['Product'].unique():
  p=x.loc[x['Product']==pr]

  for j in ['Gender','City','Quantity','Session_Duration_Minutes','Pages_Viewed','Is_Returning_Customer','Customer_Rating','Age_Group']:
    srt={}

    for i in x[j].unique():
      v_count=p.loc[p[j]==i,'Product'].value_counts()
      srt[i]=v_count.iloc[0] if not v_count.empty else 0

      # print(j,srt)
      if i not in update:
        update[i]=[]


    srt=dict(sorted(srt.items(),key=lambda item: item[1], reverse=True))
    finish=set([])

    for itm in srt.items():
      finish.add(itm[1])
      update[itm[0]].append(f'{itm[0]}{len(finish)}')


  for k in ['Product_Category','Price_Range','Product']:

    if k not in update:
      update[k]=[]

    update[k].append(p[k].unique()[0])

  # for up in update.items():
    # print(up[0],len(up[1]))
  # print('_+'*50)

In [ ]:
for i in update.items():
  print(i[0],len(i[1]))

Male 16402
Female 16402
Other 16402
Ankara 16402
Kayseri 16402
Konya 16402
Istanbul 16402
Bursa 16402
Adana 16402
Izmir 16402
Eskisehir 16402
Gaziantep 16402
Antalya 16402
Qnt_1 16402
Qnt_5 16402
Qnt_2 16402
Qnt_3 16402
Qnt_4 16402
medium_time 16402
low_time 16402
high_time 16402
medium_view 16402
low_view 16402
high_view 16402
True 16402
False 16402
Rate_4 16402
Rate_5 16402
Rate_3 16402
Rate_2 16402
Rate_1 16402
middle 16402
young 16402
old 16402
Product_Category 16402
Price_Range 16402
Product 16402

In [ ]:
updated_df=pd.DataFrame(update)

In [ ]:
# len(update['Product_Category'])
import os
path='/content/drive/MyDrive/luminar/data_science/ML/resume/archive (1)/Use_Case_3'
path=os.path.join(path,'df_for_vectorizing.csv')
updated_df.to_csv(path,index=False)

In [ ]:
updated_df

,Male,Female,Other,Ankara,Kayseri,Konya,Istanbul,Bursa,Adana,Izmir,...,Rate_5,Rate_3,Rate_2,Rate_1,middle,young,old,Product_Category,Price_Range,Product
0,Male1,Female2,Other2,Ankara1,Kayseri2,Konya2,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Books,low_price,Books:1525
1,Male1,Female2,Other2,Ankara2,Kayseri1,Konya2,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Books,medium_price,Books:189
2,Male1,Female1,Other2,Ankara2,Kayseri1,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Books,low_price,Books:1796
3,Male2,Female1,Other2,Ankara2,Kayseri2,Konya1,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Books,low_price,Books:1816
4,Male1,Female2,Other2,Ankara1,Kayseri2,Konya2,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Books,medium_price,Books:103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16397,Male2,Female1,Other2,Ankara2,Kayseri2,Konya1,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Electronics,low_price,Electronics:886
16398,Male1,Female2,Other2,Ankara2,Kayseri2,Konya2,Istanbul1,Bursa2,Adana2,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Electronics,low_price,Electronics:689
16399,Male2,Female1,Other2,Ankara2,Kayseri2,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_52,Rate_32,Rate_21,Rate_12,middle2,young1,old2,Electronics,low_price,Electronics:617
16400,Male2,Female1,Other2,Ankara2,Kayseri2,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Electronics,low_price,Electronics:670
16401,Male2,Female1,Other2,Ankara2,Kayseri2,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Electronics,medium_price,Electronics:295

In [ ]:
updated_df=pd.read_csv('/content/drive/MyDrive/luminar/data_science/ML/resume/archive (1)/Use_Case_3/df_for_vectorizing.csv')

In [ ]:
updated_df

,Male,Female,Other,Ankara,Kayseri,Konya,Istanbul,Bursa,Adana,Izmir,...,Rate_5,Rate_3,Rate_2,Rate_1,middle,young,old,Product_Category,Price_Range,Product
0,Male1,Female2,Other2,Ankara1,Kayseri2,Konya2,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Books,low_price,Books:1525
1,Male1,Female2,Other2,Ankara2,Kayseri1,Konya2,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Books,medium_price,Books:189
2,Male1,Female1,Other2,Ankara2,Kayseri1,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Books,low_price,Books:1796
3,Male2,Female1,Other2,Ankara2,Kayseri2,Konya1,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Books,low_price,Books:1816
4,Male1,Female2,Other2,Ankara1,Kayseri2,Konya2,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Books,medium_price,Books:103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16397,Male2,Female1,Other2,Ankara2,Kayseri2,Konya1,Istanbul2,Bursa2,Adana2,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Electronics,low_price,Electronics:886
16398,Male1,Female2,Other2,Ankara2,Kayseri2,Konya2,Istanbul1,Bursa2,Adana2,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Electronics,low_price,Electronics:689
16399,Male2,Female1,Other2,Ankara2,Kayseri2,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_52,Rate_32,Rate_21,Rate_12,middle2,young1,old2,Electronics,low_price,Electronics:617
16400,Male2,Female1,Other2,Ankara2,Kayseri2,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_52,Rate_32,Rate_22,Rate_12,middle2,young1,old2,Electronics,low_price,Electronics:670
16401,Male2,Female1,Other2,Ankara2,Kayseri2,Konya2,Istanbul2,Bursa2,Adana1,Izmir2,...,Rate_51,Rate_32,Rate_22,Rate_12,middle1,young2,old2,Electronics,medium_price,Electronics:295

In [ ]:
x.shape

combine

In [ ]:
updated_df.columns

Index(['Male', 'Female', 'Other', 'Ankara', 'Kayseri', 'Konya', 'Istanbul',
       'Bursa', 'Adana', 'Izmir', 'Eskisehir', 'Gaziantep', 'Antalya', 'Qnt_1',
       'Qnt_5', 'Qnt_2', 'Qnt_3', 'Qnt_4', 'medium_time', 'low_time',
       'high_time', 'medium_view', 'low_view', 'high_view', 'True', 'False',
       'Rate_4', 'Rate_5', 'Rate_3', 'Rate_2', 'Rate_1', 'middle', 'young',
       'old', 'Product_Category', 'Price_Range', 'Product'],
      dtype='object')

In [ ]:
comb=updated_df['Price_Range']
for col in updated_df.columns.unique():
  if col!='Price_Range' and col!='Product':
    comb=comb+' '+updated_df[col]

In [ ]:
vec=TfidfVectorizer()
x_vector=vec.fit_transform(comb)

In [ ]:
x_vector=x_vector.toarray()

In [ ]:
x_vector.ndim

2

In [ ]:
updated_df.ndim

2

In [ ]:
x_vector.ndim

2

In [ ]:
for i,j in zip(updated_df['Product'],x_vector):
  print(i,j)
  break

Books:1525 [0.         0.12155895 0.         0.32680955 0.         0.
 0.         0.12100263 0.         0.         0.34907667 0.
 0.12449716 0.         0.         0.         0.1170981  0.
 0.         0.12656185 0.         0.         0.19318114 0.
 0.         0.         0.12053745 0.         0.         0.
 0.12245484 0.         0.         0.11921162 0.         0.
 0.         0.14664796 0.         0.         0.12714653 0.
 0.         0.11813906 0.         0.         0.12005952 0.
 0.13416994 0.         0.1306879  0.         0.         0.12860193
 0.         0.19239489 0.         0.         0.14098897 0.
 0.13525701 0.         0.21953845 0.         0.         0.11588984
 0.         0.         0.11402504 0.         0.28938741 0.
 0.         0.         0.13757477 0.         0.         0.13788402
 0.         0.         0.13816825 0.         0.         0.13843591
 0.         0.         0.11763532 0.         0.         0.12281521
 0.         0.         0.13188823 0.         0.22886424 0.
 0.         0.         0.16499029 0.         0.         0.
 0.12563266 0.         0.         0.21568394]

Convert product name as keys its vectors as values in a dictionary

In [ ]:
product_dictionary={}
for i,j in zip(updated_df['Product'],x_vector):
  product_dictionary[i]=[j]

Taking first 5 nearby vecotor products using cosine similarity

In [ ]:
def recommend(item):
  if  item in product_dictionary:
    v_in=product_dictionary[item]
    cosine_dit={}
    for prd,v_check in product_dictionary.items():
      if prd!=item:
        cosine_dit[prd]=cosine_similarity(v_in,v_check)[0][0]
    result=sorted(cosine_dit.items(),key=lambda a:a[1],reverse=True)
    return [i[0] for i in result[:5]]
  else:
    return 'not_available'

In [ ]:
test_in=product_dictionary['Books:1']
test_chck=product_dictionary['Books:2']

In [ ]:
recommend('Books:3')

['Books:352', 'Books:16', 'Electronics:23', 'Sports:32', 'Books:9']

In [ ]:
product_dictionary['Books:1'][0].shape